steps:
  - name: node:12.16.1
    entrypoint: yarn
    args: ["install"]
  - name: node:12.16.1
    entrypoint: yarn
    args: ["test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcloud-nodejs-demo", "."]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--image-url=gcr.io/$PROJECT_ID/gcloud-nodejs-demo"]

images:
  - "gcr.io/$PROJECT_ID/gcloud-nodejs-demo"
